### ISSUE TITLE
Link in "D8 Library Desugaring" post now "dead"

### ISSUE THREAD

**Issue by cketti** [JakeWharton/jakewharton.com#24]
The post "D8 Library Desugaring" contains the following text:

> For now the best list of backported types is in the [Android Studio preview features](https://developer.android.com/studio/preview/features#j8-desugar) and the best list of backported APIs on existing types are […]

The preview features page no longer contains the relevant information. Maybe you could point to this page instead:

https://developer.android.com/studio/releases/gradle-plugin#j8-library-desugaring

**Comment by JakeWharton** [comment]
Thanks will fix. CC #8.

**Comment by JakeWharton** [comment]
dd0cb6bdb09621f8f8be9c1e769122724ac85188
