### ISSUE TITLE
Code samples look weird

### ISSUE THREAD

**Issue by urgentx** [JakeWharton/jakewharton.com#28]
The background only covers the text, not the whole div. Might be a problem with rouge highlighting library.

[See image here](https://imgur.com/tuVzJ8a)

**Comment by JakeWharton** [comment]
Browser and OS versions?

**Comment by urgentx** [comment]
MacOS Catalina 10.15.5
Chrome Version 83.0.4103.116

**Comment by JakeWharton** [comment]
Thanks I'm just dumb.

6709cb6dd8c67f378fd47e262d0af1fb5c6724f9
